name: GitLeaks Scan

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ development ]

permissions: 
  contents: read
  packages: read

jobs:
  call-central-gitleaks:
    uses: Code-Syndicate-Latam/org-security/.github/workflows/gitleaks.yml@main
    permissions: inherit
    secrets: inherit
