name: GitLeaks Scan

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

permissions: inherit

jobs:
  call-central-gitleaks:
    uses: Code-Syndicate-Latam/org-security/.github/workflows/gitleaks.yml@main
