name: GitLeaks Scan

on:
  pull_request:
    branches: [ main, developmen ]
  push:
    branches: [ main, development ]

permissions:
  contents: read

jobs:
  call-central-gitleaks:
    uses: Code-Syndicate-Latam/org-security/.github/workflows/gitleaks.yml@main
