name: GitLeaks Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  call-central-gitleaks:
    uses: Code-Syndicate-Latam/org-security/.github/workflows/gitleaks.yml@main
    with:
      severity: high
      branches: "main"